server:
  port: 8080

spring:

  # 샘플 데이터 설정
#  profiles:
#    active: real

#  jpa:
#    hibernate:
#      ddl-auto: 'create-drop'
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#    defer-datasource-initialization: true
#    database: mysql
#


  datasource:
    url: jdbc:mysql://localhost:3306/cyworld?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jack
    password: jack



  # file
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # Swagger
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  # Session
  session:
    store-type: jdbc

  config:
    import:
      - classpath:/real-application.yml


logging:


  file:
    name: ${user.dir}/log/event-check.log
    max-history: 7
    max-size: 10MB
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


