spring:
  profiles: p6spy

# jpa
  jpa:
    hibernate:
      ddl-auto: 'none'
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database: mysql



  # DB
#  decorator:
#    datasource:
#      url: jdbc:mysql://localhost:3306/cyworld?useSSl=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: jack
#      password: jack
#      p6spy:
#        enable-logging: true

  logging:
    level:
      org.hibernate.sql: debug
      org.hibernate.type: trace
